#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
setopt NO_HUP
setopt NO_FLOW_CONTROL
setopt NO_CLOBBER
setopt NO_CASE_GLOB
setopt NUMERIC_GLOB_SORT

export TERM=screen-256color
alias gpg='gpg2'
export EDITOR=vim
export ARMGCC_DIR=~/toolchain/gcc-arm-none-eabi-5_4-2016q3

# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/tools/google-cloud-sdk/path.zsh.inc' ]; then source '~/tools/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/tools/google-cloud-sdk/completion.zsh.inc' ]; then source '~/tools/google-cloud-sdk/completion.zsh.inc'; fi
