#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
setopt NO_HUP
setopt NO_FLOW_CONTROL
setopt NO_CLOBBER
setopt NO_CASE_GLOB
setopt NUMERIC_GLOB_SORT

export TERM=xterm-256color
alias gpg='gpg2'
export EDITOR=vim
export ARMGCC_DIR=$HOME/toolchains/sdk_armgcc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/tools/google-cloud-sdk/path.zsh.inc' ]; then source '~/tools/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/tools/google-cloud-sdk/completion.zsh.inc' ]; then source '~/tools/google-cloud-sdk/completion.zsh.inc'; fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="/usr/local/opt/python/libexec/bin:/Applications/SEGGER/JLink:/usr/local/bin:$PATH:$HOME/.rvm/bin:$HOME/Tools/connectiq-sdk/bin:$HOME/bin:$HOME/Library/Python/2.7/bin"
export PATH=$PATH:"$HOME/Downloads/clang+llvm-10.0.0-x86_64-apple-darwin/bin"
export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
export GNUARMEMB_TOOLCHAIN_PATH=~/toolchains/gcc-arm-none-eabi-8-2018-q4-major

# set history size
export HISTSIZE=10000
# save history after logout
export SAVEHIST=10000
# history file
export HISTFILE=~/.zhistory
# append into history file
setopt INC_APPEND_HISTORY
# save only one command if 2 common are same and consistent
setopt HIST_IGNORE_DUPS
# add timestamp for each entry
setopt EXTENDED_HISTORY

alias youtube-dl='youtube-dl -f bestvideo+bestaudio --recode-video mp4'

# hpm-sdk
export GNURISCV_TOOLCHAIN_PATH=~/toolchains/riscv

alias grep='grep -n'
